name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Full Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Check Conda
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python --version

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install -r develop.txt
          python -m pip install -r docs/requirements.txt
          python -m pip install astropy scikit-image scikit-learn
          python -m pip install tensorflow>=2.4.1
          python -m pip install twine
          python -m pip install .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          export PATH=/usr/share/miniconda/bin:$PATH
          python setup.py test

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: pytest.xml

      - name: Check Distribution
        shell: bash -l {0}
        run: |
          python setup.py sdist
          twine check dist/*

      - name: Check API Documentation build
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pandoc
          sphinx-apidoc -t docs/_templates -feTMo docs/source modopt
          sphinx-build -b doctest -E docs/source docs/_build

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests

  test-basic:
    name: Basic Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install -r develop.txt
          python -m pip install astropy scikit-image scikit-learn
          python -m pip install .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          export PATH=/usr/share/miniconda/bin:$PATH
          python setup.py test
